name: Generate JSDoc

on:
  push:
    branches: 
      - '**'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # Needed to avoid GitHub auto adding a token

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install

    - name: Install JSDoc
      run: npm install --save-dev jsdoc

    - name: Generate JSDoc
      run: ./node_modules/.bin/jsdoc ./Fortune-Teller/js

    - name: Commit and push to the triggering branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout $(echo ${GITHUB_REF#refs/heads/})
        git add -A
        git commit -m "Generated JSDoc"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cse110-sp23-group13/cse110-sp23-group13.git $(echo ${GITHUB_REF#refs/heads/})
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
